// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCv7g8X-O4dRlTpfQqx6BrHY9pTLDS0lM',
    appId: '1:980193949248:web:fa19658939daf27b8e51a5',
    messagingSenderId: '980193949248',
    projectId: 'phone-auth-demoproj',
    authDomain: 'phone-auth-demoproj.firebaseapp.com',
    storageBucket: 'phone-auth-demoproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW3LpUNxltXatgnea01-JCcx0WTgoCx8A',
    appId: '1:980193949248:android:ef0dc173ae0b584c8e51a5',
    messagingSenderId: '980193949248',
    projectId: 'phone-auth-demoproj',
    storageBucket: 'phone-auth-demoproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_IzMQVME0nhegs9cXg_rKTxhY96sQTI',
    appId: '1:980193949248:ios:de3868ce1d5ab1b18e51a5',
    messagingSenderId: '980193949248',
    projectId: 'phone-auth-demoproj',
    storageBucket: 'phone-auth-demoproj.appspot.com',
    iosClientId: '980193949248-v4m591ersbbfud5hboq44t6s6rccs66c.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthDemo',
  );
}
